package org.i9.GCViz.CombinedClustering;

public class DBGraphSettingPanel extends javax.swing.JPanel {

    private CombinedClustering combinedClustering;

    public DBGraphSettingPanel() {
        initComponents();
        combinedClustering = new CombinedClustering();
        k_min.setText("" + combinedClustering.getK());
        epsilon.setText("" + combinedClustering.getEpsilon());
        min_pts.setText("" + combinedClustering.getMin_pts());
        r_dim.setText("" + combinedClustering.getR_dim());
        r_obj.setText("" + combinedClustering.getR_obj());
        s_min.setText("" + combinedClustering.getS_min());
        path.setText("dbcsc.found");
    }

    public void setup() {
                        
    }
     public String getPath() {
        return path.getText();
    }

     public CombinedClustering getCombinedClustering(){
         return combinedClustering;
     }
    public void unsetup() {
        
        try {
            combinedClustering.setK(Integer.parseInt(k_min.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setEpsilon(Double.parseDouble(epsilon.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setMin_pts(Integer.parseInt(min_pts.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setR_dim(Double.parseDouble(r_dim.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setR_obj(Double.parseDouble(r_obj.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setS_min(Integer.parseInt(s_min.getText()));
        } catch (Exception e) {
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultFileChooser = new javax.swing.JFileChooser();
        jLabel5 = new javax.swing.JLabel();
        k_min = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        epsilon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        min_pts = new javax.swing.JTextField();
        s_min = new javax.swing.JTextField();
        r_dim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        r_obj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        resultFileChooser.setDialogTitle(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.resultFileChooser.dialogTitle")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.jLabel5.text")); // NOI18N

        k_min.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.k_min.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.jLabel1.text")); // NOI18N

        epsilon.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.epsilon.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.jLabel2.text")); // NOI18N

        min_pts.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.min_pts.text")); // NOI18N

        s_min.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.s_min.text")); // NOI18N

        r_dim.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.r_dim.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.jLabel3.text")); // NOI18N

        r_obj.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.r_obj.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.jLabel4.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.jLabel6.text")); // NOI18N

        path.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.path.text")); // NOI18N
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        jButton1.setText(org.openide.util.NbBundle.getMessage(DBGraphSettingPanel.class, "DBGraphSettingPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(k_min, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(min_pts, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(epsilon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r_dim, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r_obj, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(s_min, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(k_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(epsilon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(min_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_dim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_obj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        
                 
    }//GEN-LAST:event_pathActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int returnVal = resultFileChooser.showOpenDialog(this);
        if(returnVal == resultFileChooser.APPROVE_OPTION){
            path.setText(resultFileChooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField epsilon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField k_min;
    private javax.swing.JTextField min_pts;
    private javax.swing.JTextField path;
    private javax.swing.JTextField r_dim;
    private javax.swing.JTextField r_obj;
    private javax.swing.JFileChooser resultFileChooser;
    private javax.swing.JTextField s_min;
    // End of variables declaration//GEN-END:variables
}
