package org.i9.GCViz.CombinedClustering;


public class GamerSettingPanel extends javax.swing.JPanel {

    private CombinedClustering combinedClustering;

    public GamerSettingPanel() {
        combinedClustering = new CombinedClustering();
        initComponents();
        n_min.setText("" + combinedClustering.getN_min());
        gamma_min.setText("" + combinedClustering.getGamma_min());
        s_min.setText("" + combinedClustering.getS_min());
        param_a.setText("" + combinedClustering.getParam_a());
        param_b.setText("" + combinedClustering.getParam_b());
        param_c.setText("" + combinedClustering.getParam_c());
        param_r.setText("" + combinedClustering.getR_obj());
        param_s.setText("" + combinedClustering.getR_dim());
        w_max.setText("" + combinedClustering.getW_max());
        
    }

    public void setup() {
            
    }
    
    public CombinedClustering getCombinedClustering(){
         return combinedClustering;
     }
    
    public String getPath() {
        return path.getText();
    }

    public void unsetup() {
        try {
            combinedClustering.setN_min(Integer.parseInt(n_min.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setGamma_min(Double.parseDouble(gamma_min.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setS_min(Integer.parseInt(s_min.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setParam_a(Double.parseDouble(param_a.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setParam_b(Double.parseDouble(param_b.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setParam_c(Double.parseDouble(param_c.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setR_obj(Double.parseDouble(param_r.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setR_dim(Double.parseDouble(param_s.getText()));
        } catch (Exception e) {
        }
        try {
            combinedClustering.setW_max(Double.parseDouble(w_max.getText()));
        } catch (Exception e) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultFileChooser = new javax.swing.JFileChooser();
        jLabel5 = new javax.swing.JLabel();
        n_min = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gamma_min = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        s_min = new javax.swing.JTextField();
        param_c = new javax.swing.JTextField();
        param_a = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        param_b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        param_r = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        param_s = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        w_max = new javax.swing.JTextField();
        path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        resultFileChooser.setDialogTitle(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.resultFileChooser.dialogTitle")); // NOI18N
        resultFileChooser.setToolTipText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.resultFileChooser.toolTipText")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel5.text")); // NOI18N

        n_min.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.n_min.text")); // NOI18N
        n_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_minActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel1.text")); // NOI18N

        gamma_min.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.gamma_min.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel2.text")); // NOI18N

        s_min.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.s_min.text")); // NOI18N

        param_c.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.param_c.text")); // NOI18N

        param_a.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.param_a.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel3.text")); // NOI18N

        param_b.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.param_b.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel4.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel6.text")); // NOI18N

        param_r.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.param_r.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel7.text")); // NOI18N

        param_s.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.param_s.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jLabel9.text")); // NOI18N

        w_max.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.w_max.text")); // NOI18N

        path.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.path.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(GamerSettingPanel.class, "GamerSettingPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(n_min, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(s_min, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gamma_min, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(param_a, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(param_b, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(param_c, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(param_r, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(param_s, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(w_max, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(n_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(gamma_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(param_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(param_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(param_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(param_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(param_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void n_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_minActionPerformed
       
    }//GEN-LAST:event_n_minActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int returnVal = resultFileChooser.showOpenDialog(this);
        if(returnVal == resultFileChooser.APPROVE_OPTION){
            path.setText(resultFileChooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gamma_min;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n_min;
    private javax.swing.JTextField param_a;
    private javax.swing.JTextField param_b;
    private javax.swing.JTextField param_c;
    private javax.swing.JTextField param_r;
    private javax.swing.JTextField param_s;
    private javax.swing.JTextField path;
    private javax.swing.JFileChooser resultFileChooser;
    private javax.swing.JTextField s_min;
    private javax.swing.JTextField w_max;
    // End of variables declaration//GEN-END:variables
}
